# Generated by Django 3.2 on 2021-07-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productscart',
            options={'verbose_name': 'Product in Cart', 'verbose_name_plural': 'Products in Carts'},
        ),
    ]
