# Generated by Django 3.2.1 on 2021-05-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'transferencia'), ('debito', 'debito'), ('credito', 'credito')], default=None, max_length=50)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECommerce.carrito')),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='mail',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
