# Generated by Django 3.2.1 on 2021-06-03 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce', '0002_auto_20210526_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AddField(
            model_name='carrito',
            name='productoVenta',
            field=models.ManyToManyField(to='ECommerce.Producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='precio_final',
            field=models.IntegerField(default=None),
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('product_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECommerce.producto')),
            ],
        ),
    ]
