# Generated by Django 3.2.1 on 2021-06-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce', '0003_auto_20210603_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='productoVenta',
            new_name='producto_venta',
        ),
        migrations.AddField(
            model_name='carrito',
            name='monto_total',
            field=models.IntegerField(default=None),
        ),
    ]
