# Generated by Django 3.2.1 on 2021-06-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce', '0004_auto_20210603_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='monto_total',
            field=models.IntegerField(default=0),
        ),
    ]
